baseURL = 'https://example.org/'
languageCode = 'de'
title = 'EndOf10-HH'

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menus.main]]
    name = "About us"
    url = "/about"
    weight = 2