baseURL = "https://m03315.github.io/nomad-tech/"
defaultContentLanguage = "de"
theme = "nomad-tech"

[pagination]
  pagerSize = 6

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "EndOf10-HH"
  logo = "EndOf10-HH"
  subtitle = ""
  description = ""